[FLINK-17490] Add training page
apache/flink-web pull request #333
Opened 2020-05-01 11:24 UTC by alpinegizmo

Now that the documentation has a training section, it would be good to help folks find it by promoting it from the project website.

This adds training.md and training.zh.md, and adds a Training entry to the site navigation.

![image](https://user-images.githubusercontent.com/43608/80802203-ffc6a400-8bae-11ea-927a-2f2db8b79028.png)

2020-05-01 11:26 UTC, alpinegizmo commented
I've created https://issues.apache.org/jira/browse/FLINK-17491 for the Chinese translation.

2020-05-01 15:23 UTC, morsapaes commented
Hey, David! Thanks a lot for doing the whole integration of the training — it's a super valuable resource that indeed deserves more attention.

What about linking this from the "Getting Started" dropdown, instead? I'm afraid we're starting to accumulate quite a lot of disparate links in the navigation bar. Once the discussion to revamp the landing page kicks in, then we could make sure that the self-paced training is properly highlighted in there.

2020-05-01 15:40 UTC, XBaith commented
> Hey, David! Thanks a lot for doing the whole integration of the training — it's a super valuable resource that indeed deserves more attention.
> 
> What about linking this from the "Getting Started" dropdown, instead? I'm afraid we're starting to accumulate quite a lot of disparate links in the navigation bar. Once the discussion to revamp the landing page kicks in, then we could make sure that the self-paced training is properly highlighted in there.

Good idea.I also think that putting "Training" in "Get Started" will help users quickly and systematically learn with Flink

2020-05-04 12:14 UTC, alpinegizmo commented
@morsapaes @XBaith I've changed it, based on your feedback. 

![image](https://user-images.githubusercontent.com/43608/80964626-82e73480-8e11-11ea-85f6-b9d2d920bef0.png)

2020-05-04 14:20 UTC, morsapaes commented
Thanks, David! I think this makes it more intuitive to find. 👌

2020-05-04 18:51 UTC, XBaith commented
Thank you @alpinegizmo .

2020-05-05 14:16 UTC, NicoK requested changes
I like the page +1

(seems like titles are always separated by `<hr>` ... once this is added, we can go ahead)

2020-05-05 14:16 UTC, NicoK commented on training.md
> +
Other pages seem to add this to titles; we should be consistent
```suggestion

<hr/>

```

2020-05-05 14:16 UTC, NicoK commented on training.zh.md
> +
Other pages seem to add this to titles; we should be consistent
```suggestion

<hr/>

```

2020-05-05 14:41 UTC, NicoK approved these changes

2020-05-05 15:24 UTC, closed without merging