[FLINK-27049] Add 'What is Flink Kubernetes Operator?' link to flink website
apache/flink-web pull request #525
Opened 2022-04-06 13:16 UTC by SteNicholas

Similar to statefun and ml projects we should also add a "What is Flink Kubernetes Operator?" link to the menu pointing to the doc site. 

**The brief change log**

- Add 'What is Flink Kubernetes Operator?' link to flink website.

2022-04-06 13:17 UTC, SteNicholas commented
@gyfora,  PTAL.

2022-04-06 17:31 UTC, gyfora commented
This doesnt look right ... aren't the HTML files generated? I think we should only need to add this to 1-2 files and the rest would be generated

2022-04-07 03:51 UTC, SteNicholas commented
@gyfora, the `i18n.yml` and `navBar.html` should be added and the changes of other files in `content` directory are generated by build script. I have added these changes in this pull request. @mbalassi , PTAL for the changes in `content`.

2022-07-06 05:58 UTC, gyfora commented
@SteNicholas Could you please update this PR? 

@mbalassi I would appreciate if you could take a look once it's ready, because I cant test this locally :/

2022-07-06 08:08 UTC, SteNicholas commented
@gyfora, I have updated this PR and the changes are generated by running `docker-build.sh`. PTAL.

2022-07-06 08:20 UTC, mbalassi commented
@SteNicholas roger, taking a look now.

2022-07-06 09:22 UTC, SteNicholas commented
@mbalassi, any problem?

2022-07-06 09:23 UTC, mbalassi requested changes
@SteNicholas please link 
https://nightlies.apache.org/flink/flink-kubernetes-operator-docs-stable/ instead of the 0.1 release.
Also nit: let us write "What is the Flink Kubernetes Operator?" instead, it does not fit into a single line anyway.
<img width="262" alt="Screenshot 2022-07-06 at 11 21 29" src="https://user-images.githubusercontent.com/5990983/177517411-25369d33-39c8-4d7a-a7b3-3f4efa388677.png">

2022-07-06 11:08 UTC, SteNicholas commented
@mbalassi, I have addressed above comments. PTAL.

2022-07-06 13:54 UTC, mbalassi approved these changes
LGTM, merging. @SteNicholas for future PRs to this repo I kindly suggest to separate the change to the source and the build itself to 2 separate commits as you can see in the history usually:
https://github.com/apache/flink-web/commits/asf-site
(See `Rebuild website` commits)
I appreciate that you intended to help @gyfora with providing the build, so I am not asking you to do it for this change.

2022-07-06 13:54 UTC, merged